app:
  build: .
  container_name: monarch_app
  restart: always
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: YZDxiXfIhOxZtgqGMCofDyZvYnoZHypL
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
    SERVER_PORT: 8080
  ports:
    - "8080:8080"
